# Generated by Django 3.0.3 on 2020-02-20 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biography',
            options={'verbose_name': 'Biography', 'verbose_name_plural': 'Biographies'},
        ),
        migrations.AlterField(
            model_name='author',
            name='date_birth',
            field=models.DateField(verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books_shelf.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(verbose_name='Published date'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Name of genre'),
        ),
    ]
